@startuml
!pragma layout smetana

'(Main) <|-- (GameController)
'(GameController) <|-- (Player)
'(GameController) <|-- (Level)
'(GameController) <|-- (FileIO)

(Player) *-- (Storage)
(Storage) *-- (Item)

(Level) *-- (Fields)
(Level) *-- (Player)


'(FileIO) <|-- (IO)

(Fields) <|-- (LootChest)
(Fields) <|-- (WeaponSmith)
(Fields) <|-- (MonsterBattle)
(Fields) <|-- (ItemShop)
(Fields) *-- (Item)

(MonsterBattle) *-- (Monster)
'(MonsterBattle) <|-- (BattleSystem)


@enduml
