@startuml
'https://plantuml.com/class-diagram

!pragma layout smetana

class main {
}

class Player {
- int HP
- int damage
- String playerName
- Storage storage
}

class Monsters {
int hitPoints
int damage
String monsterName
}

class BattleSystem {
int turn

attack()
heal()
useItem()
escapeBattle()
}

class Storage {
ArrayList<Item> playerItems

loadPlayerItemsFromDBToArrayList()
}

class Levels {
int levelCounter
BattleSystem battleSystem
Monsters monsters
}

class Item {
String itemName
int id
String rarity
ArrayList<Item> itemTypes

createItem(String selectRandomItemRarity, String selectRandomItemType)
String selectRandomItemRarity()
String selectRandomItemType()
loadItemsFromDBToArrayList()
}

class LootChest {
int gold
Item item

openLootChest()
}

class Tiles {

}

class MonsterBattle {
}

class ItemShop {
}

class Options {
}


main <|-- Levels
Levels <|-- Player
Levels <|-- Options
Player <|-- Storage
Player <|-- Item
LootChest <|-- Item
Levels <|-- LootChest
Levels <|-- Tiles
Tiles <|-- ItemShop
Tiles <|-- WeaponSmith
Tiles <|-- MonsterBattle
MonsterBattle <|-- Monsters
MonsterBattle <|-- BattleSystem

@enduml